"""Gurki hinzufügen

Revision ID: a7336df5d8b8
Revises: 07b4458b258c
Create Date: 2023-06-13 23:51:14.762986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7336df5d8b8'
down_revision = '07b4458b258c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gurki', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('gurki')

    # ### end Alembic commands ###
